DROP TABLE TBL_DOCUMENTS;

CREATE TABLE TBL_DOCUMENTS(
  DOC_ID INT NOT NULL,
  DOC_NAME VARCHAR(225) NOT NULL,
  DOC_BINARY VARBINARY NOT NULL,
  
  CONSTRAINT PK_TBL_DOCUMENTS PRIMARY KEY(DOC_ID)
);
